sudo: required 
language: java
jdk:
  - oraclejdk8
script: mvn -B clean install

services:
  - docker

notifications:
  slack: 
    on_success: never
    on_failure: always
    rooms:
      - oicr:S9k4EowgQv9AnbCfEZHSzCsg

before_install:
  - docker build -t quay.io/pancancer/pcawg-bwa-mem-workflow:2.6.8_1.2 .
  - pip2.7 install --user setuptools==24.0.3

install: 
  - pip2.7 install --user cwl-runner cwltool==1.0.20160712154127 schema-salad==1.14.20160708181155 avro==1.8.1

script: 
  - cwltool --non-strict --print-pre Dockstore.cwl
# cannot run, proper run would take too long - cwltool --non-strict Dockstore.cwl Dockstore_cwl.json
